name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate changelog
        run: |
          git log $(git describe --tags --abbrev=0 @^)..@ --pretty=format:"- %s" > CHANGELOG.md || echo "No previous tags"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
